//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stanza.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stanza.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You know you can&apos;t be here peter..
        /// </summary>
        internal static string ArbitraryFailureA {
            get {
                return ResourceManager.GetString("ArbitraryFailureA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does this look like a McDonald&apos;s?.
        /// </summary>
        internal static string ArbitraryFailureB {
            get {
                return ResourceManager.GetString("ArbitraryFailureB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s a number of characters very close to Pi, uh oh!.
        /// </summary>
        internal static string AuxiliaryFailureA {
            get {
                return ResourceManager.GetString("AuxiliaryFailureA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must not be empty..
        /// </summary>
        internal static string BasicFailureA {
            get {
                return ResourceManager.GetString("BasicFailureA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must not be one character in length..
        /// </summary>
        internal static string BasicFailureB {
            get {
                return ResourceManager.GetString("BasicFailureB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must not be null..
        /// </summary>
        internal static string EssentialFailureA {
            get {
                return ResourceManager.GetString("EssentialFailureA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s an unlucky number of characters you have there..
        /// </summary>
        internal static string ExampleFailureA {
            get {
                return ResourceManager.GetString("ExampleFailureA", resourceCulture);
            }
        }
    }
}
